### ISSUE TITLE
TypeError: The compressed data passed is corrupted

### ISSUE THREAD

**Issue by arpanr** [LegendaryEmoji/Music-Bot#19]
On DigitalOcean Ubuntu  VPS with node v14.6.0

when I use `play attention `

TypeError: The compressed data passed is corrupted
    at Decoder._decode (/home/ubuntu/discord-bot/node_modules/prism-media/src/opus/Opus.js:64:25)
    at Decoder._transform (/home/ubuntu/discord-bot/node_modules/prism-media/src/opus/Opus.js:204:22)
    at Decoder.Transform._read (_stream_transform.js:205:10)
    at Decoder.Transform._write (_stream_transform.js:193:12)
    at writeOrBuffer (_stream_writable.js:352:12)
    at Decoder.Writable.write (_stream_writable.js:303:10)
    at PassThrough.ondata (_stream_readable.js:713:22)
    at PassThrough.emit (events.js:314:20)
    at PassThrough.EventEmitter.emit (domain.js:486:12)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:279:9)
    at PassThrough.Readable.push (_stream_readable.js:218:10)
    at PassThrough.Transform.push (_stream_transform.js:166:32)
    at PassThrough.afterTransform (_stream_transform.js:101:10)
    at PassThrough._transform (_stream_passthrough.js:46:3)
    at PassThrough.Transform._read (_stream_transform.js:205:10)
    at PassThrough.Transform._write (_stream_transform.js:193:12)
    at writeOrBuffer (_stream_writable.js:352:12)
    at PassThrough.Writable.write (_stream_writable.js:303:10)
    at PassThrough.ondata (_stream_readable.js:713:22)
    at PassThrough.emit (events.js:326:22)
    at PassThrough.EventEmitter.emit (domain.js:486:12)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:279:9)
    at PassThrough.Readable.push (_stream_readable.js:218:10)
    at PassThrough.Transform.push (_stream_transform.js:166:32)
    at PassThrough.afterTransform (_stream_transform.js:101:10)
    at PassThrough._transform (_stream_passthrough.js:46:3)
    at PassThrough.Transform._read (_stream_transform.js:205:10)
    at PassThrough.Transform._write (_stream_transform.js:193:12)
    at writeOrBuffer (_stream_writable.js:352:12)
    at PassThrough.Writable.write (_stream_writable.js:303:10)
    at IncomingMessage.ondata (_stream_readable.js:713:22)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:486:12)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:279:9)
    at IncomingMessage.Readable.push (_stream_readable.js:218:10)
    at HTTPParser.parserOnBody (_http_common.js:132:24)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket.EventEmitter.emit (domain.js:486:12)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:279:9)
    at TLSSocket.Readable.push (_stream_readable.js:218:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)

**Comment by LegendaryEmoji** [comment]
you can try updating the packages (ytdl-core, dsicord.js, @discordjs/opus, etc)

it will be fixed in next update (98% stuff is going to get fixed in update)

**Comment by arpanr** [comment]
yes I have the latest versions of these packages

**Comment by arpanr** [comment]
Any idea when the new update is coming out? @LegendaryEmoji

**Comment by LegendaryEmoji** [comment]
its going to take alot of time and not sure
